Update C# conventions
howest-gp/conventions pull request #8
Opened 2023-04-17 12:54 UTC by hermandebeukelaer

Enkele zaken toegevoegd aan de C# conventies naar aanleiding van moduleoverleg PRB/PRA.

2023-04-17 13:17 UTC, janiek-howest requested changes
Je hebt wel nog wat werk, goed bezig.

2023-04-17 13:17 UTC, janiek-howest commented on C# conventions.md
>    public static string BankName;
@hermandebeukelaer moet dit niet met kleine letter? En ook niet private?

2023-04-17 13:17 UTC, janiek-howest commented on C# conventions.md
> +  public static decimal Reserves;
kan je deze verwijderen?

2023-04-17 13:17 UTC, janiek-howest commented on C# conventions.md
Misschien meot je er ook nog een gewoon veld aan toe voegen. En misschein voor de duidelijkheid ook tussen de properties, aangezien daar de volgorde niet uitmaakt... En mss ook eens een full property

2023-04-17 20:08 UTC, janiek-howest approved these changes

2023-04-18 06:54 UTC, sigged approved these changes

2023-04-18 07:00 UTC, merged